#!/bin/bash

exitflg=0

if type fontforge > /dev/null 2>&1; then
    echo '[DSEG]Fontforge is detected.'
else
    echo '[DSEG]Please install fontforge.(https://fontforge.github.io/en-US/)'
    exitflg=1
fi

if type woff2_compress > /dev/null 2>&1; then
    echo '[DSEG]Google woff2 is detected.'
else
    echo '[DSEG]Please install google woff2.(https://github.com/google/woff2)'
    exitflg=1
fi

if [ $exitflg -eq 1 ]; then
    exit 1
else
    mkdir -p fonts

    fontforge -lang=ff -c 'Open($1); Generate($2)' src/DSEG7ClassicMini-BoldItalic-hidden-hyphen.sfd fonts/DSEG7ClassicMini-BoldItalic-hidden-hyphen.ttf >&/dev/null
    woff2_compress fonts/DSEG7ClassicMini-BoldItalic-hidden-hyphen.ttf >&/dev/null
    rm fonts/DSEG7ClassicMini-BoldItalic-hidden-hyphen.ttf

    fontforge -lang=ff -c 'Open($1); Generate($2)' src/DSEG7ClassicMini-BoldItalic-hidden-hyphen-all-eight.sfd fonts/DSEG7ClassicMini-BoldItalic-hidden-hyphen-all-eight.ttf >&/dev/null
    woff2_compress fonts/DSEG7ClassicMini-BoldItalic-hidden-hyphen-all-eight.ttf >&/dev/null
    rm fonts/DSEG7ClassicMini-BoldItalic-hidden-hyphen-all-eight.ttf

    echo '[DSEG]DSEG font file is generated.'
fi
